name: Deploy with Ansible and Fetch HTML

on:
  push:
    branches:
      - main  
jobs:
  deploy:
    runs-on: ubuntu-latest  

    steps:
      - name: Checkout repository 
        uses: actions/checkout@v3

      - name: Install Ansible  
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible

      - name: Run Ansible playbook  
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: playbook.yml  
          key: ${{secrets.SSH_KEY}} 
          inventory: |
            [all]
            15.164.213.4 ansible_ssh_user=ubuntu  

  fetch-html:
    needs: deploy
    runs-on: ubuntu-latest

    steps:
      - name: Fetch HTML code from GitHub  
        uses: actions/checkout@v3
        with:
          repository: ParkHyeonBeom/Ansible   
          ref: main  
          path: /tmp/html-code 

  install-nginx:
    needs: fetch-html
    runs-on: ubuntu-latest

    steps:
      - name: Install Nginx 
        run: |
          sudo apt-get update
          sudo apt-get install -y nginx

      - name: Copy HTML code to Nginx root directory  
        run: sudo cp -r /tmp/html-code /var/www/html/
