name: Deploy with Ansible and Fetch HTML

on:
  push:
    branches:
      - main  
jobs:
  deploy:
    runs-on: ubuntu-latest  

    steps:
      - name: Checkout repository 
        uses: actions/checkout@v3

      - name: Install Ansible  
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible

      - name: Run Ansible playbook  
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: playbook.yml  
          key: ${{secrets.SSH_KEY}} 
          inventory: |
            [all]
            15.164.213.4 ansible_ssh_user=ubuntu  
            
  install-nginx:
    needs: fetch-html
    runs-on: ubuntu-latest

    steps:
      - name: Install Nginx 
        run: |
          sudo apt-get update
          sudo apt-get install -y nginx

      - name: Copy HTML code to Nginx root directory  
        run: sudo cp -r /tmp/html-code /var/www/html/
        
  fetch-html:
    needs: deploy
    runs-on: ubuntu-latest

    steps:
    - name: get code from github
      uses: appleboy/ssh-action@v0.1.9
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.REMOTE_PORT }}
        script: |
          sudo rm -rf ./Ansible
          sudo git clone https://github.com/ParkHyeonBeom/Ansible
          sudo mv -f ./Ansible/*.html /var/www/html 

  
