name: Deploy with Ansible and Fetch HTML

on:
  push:
    branches:
      - main 
jobs:
  deploy:
    runs-on: ubuntu-latest  # Ubuntu 환경에서 실행

    steps:
      - name: Checkout repository  
        uses: actions/checkout@v3

      - name: Install Ansible 
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible

      - name: Run Ansible playbook 
        with:
          playbook: playbook.yml  
          key: ${{secrets.SSH_KEY}}  
          inventory: |
            [all]
            EC2_IP_ADDRESS ansible_ssh_user=ubuntu

  fetch-html:
    needs: deploy
    runs-on: ubuntu-latest

    steps:
      - name: Fetch HTML code from GitHub 
        with:
          repository: ParkHyeonBeom/Ansible  
          ref: main 
          path: ./  

  install-nginx:
    needs: fetch-html
    runs-on: ubuntu-latest

    steps:
    - name: Install Nginx  
      run: |
        sudo apt-get update
        sudo apt-get install -y nginx

    - name: Copy HTML code to Nginx root directory  
          sudo rm -rf ./Ansible
          sudo git clone https://github.com/ParkHyeonBeom/Ansible
          sudo mv -f ./Ansible/*.html /var/www/html
